DROP TABLE IF EXISTS fleet CASCADE;
DROP TABLE IF EXISTS ship CASCADE;
DROP TABLE IF EXISTS sailor CASCADE;
DROP TABLE IF EXISTS rank CASCADE;
DROP TABLE IF EXISTS assignment CASCADE;



CREATE TABLE fleet (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(255) NOT NULL
);

CREATE TABLE ship (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(255) NOT NULL,
 date_built DATE,
 fleet_id INTEGER REFERENCES fleet(id)
);

CREATE TABLE sailor (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(255) NOT NULL,
 birthdate DATE
);

CREATE TABLE rank (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(255) NOT NULL
);

CREATE TABLE assignment (
 id SERIAL PRIMARY KEY NOT NULL,
 start_date DATE,
 end_date DATE,
 ship_id INTEGER REFERENCES ship(id),
 sailor_id INTEGER REFERENCES sailor(id),
 rank_id INTEGER REFERENCES rank(id)
);